app:
  name: "@project.artifactId@"
  version: "@project.version@"

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    nl.playground.demo.elasticsearch.client: INFO

server:
  servlet:
    context-path: "/bankservice"

# for actuator endpoints (spring boot 2)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      external-file: "/var/log/bankservice/bankservice.log"

