spring:
  profiles:
    include:
      - "default"
  data:
    elasticsearch:
      cluster-nodes: "localhost:9300"
      cluster-name: "elasticsearch"
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:banking;DB_CLOSE_DELAY=-1;MODE=DB2"
    username: "sa"
    password: "sa"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  liquibase:
    change-log: "classpath:liquibase/liquibase-changelog.xml"
    contexts: "local"

logging:
  level:
    nl.playground.demo.elasticsearch.client: DEBUG

management:
  endpoint:
    logfile:
      external-file: "logs/bankservice.log"
